-- One-time bundle for the existing hosted project: removes the empty legacy prototype
-- schema and applies supabase/migrations up to 20261003000000, in ONE transaction.
-- Paste the WHOLE file (1,040+ lines) into Supabase → SQL Editor → Run.
-- Generated on 2026-10-01 by: pnpm --silent --filter @workspace/scripts run db:bundle
-- For newer migrations, regenerate instead of editing.
-- Generated by scripts/src/bundle-migrations.ts — do not edit, regenerate instead.
begin;
set local lock_timeout = '10s';
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (version text primary key, statements text[], name text);
delete from supabase_migrations.schema_migrations where version in ('20260629151213', '20260629151226', '20260629151237', '20260629151248', '20260629151301');

-- ===== 20260527180000_drop_legacy_uuid_schema.sql =====
-- ============================================================================
-- One-off cleanup of a legacy prototype schema (UUID "profiles / courts /
-- reservation_payments") that was applied to the hosted project outside of this
-- repository on 2026-06-29. The application has never used it.
--
-- Safe by construction:
--   * On a fresh database nothing matches and this is a no-op.
--   * It only acts when the legacy marker (reservations.court_id) exists, so it can
--     never touch the application's own reservations table (which has terrain_id).
--   * It refuses to run if any legacy table holds data.
-- ============================================================================
do $$
declare
  legacy_rows bigint := 0;
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'reservations' and column_name = 'court_id'
  ) then
    return;
  end if;

  select
    (select count(*) from public.profiles) +
    (select count(*) from public.courts) +
    (select count(*) from public.reservations) +
    (select count(*) from public.reservation_players) +
    (select count(*) from public.reservation_payments) +
    (select count(*) from public.token_transactions) +
    (select count(*) from public.clubs)
  into legacy_rows;

  if legacy_rows > 0 then
    raise exception 'Legacy schema contains % rows; migrate or back them up before dropping', legacy_rows;
  end if;

  drop trigger if exists on_auth_user_created on auth.users;

  drop table if exists public.reservation_payments cascade;
  drop table if exists public.reservation_players cascade;
  drop table if exists public.reservations cascade;
  drop table if exists public.token_transactions cascade;
  drop table if exists public.courts cascade;
  drop table if exists public.clubs cascade;
  drop table if exists public.profiles cascade;

  drop function if exists public.handle_new_user() cascade;
  drop function if exists public.update_profile_token_balance() cascade;
  drop function if exists public.is_admin() cascade;

  drop type if exists public.payment_status;
  drop type if exists public.token_transaction_type;
  drop type if exists public.user_role;
  drop type if exists public.reservation_status;
end $$;
insert into supabase_migrations.schema_migrations (version, name) values ('20260527180000', 'drop_legacy_uuid_schema') on conflict (version) do nothing;

-- ===== 20260527190000_production_schema.sql =====
create extension if not exists pgcrypto;

do $$ begin
  create type public.role as enum ('admin', 'player');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.language as enum ('fr', 'ar', 'en');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.terrain_type as enum ('indoor', 'outdoor');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.reservation_status as enum ('confirmed', 'cancelled', 'pending');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.booking_type as enum ('online', 'phone', 'manual');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.booking_mode as enum ('full_court', 'own_spot');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.player_payment_type as enum ('token', 'cash');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.player_payment_status as enum ('paid', 'pending', 'refunded');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.invite_status as enum ('pending', 'accepted', 'expired', 'cancelled');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.token_type as enum ('credit', 'debit', 'adjustment');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.notification_type as enum ('booking_confirmed', 'booking_cancelled', 'tokens_added', 'reservation_reminder', 'announcement');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.tournament_status as enum ('upcoming', 'open', 'ongoing', 'completed', 'cancelled');
exception when duplicate_object then null; end $$;

create table if not exists public.users (
  id serial primary key,
  supabase_auth_id text not null unique,
  email text not null unique,
  first_name text,
  last_name text,
  phone text,
  role public.role not null default 'player',
  avatar_url text,
  token_balance integer not null default 0 check (token_balance >= 0),
  language public.language not null default 'fr',
  created_at timestamp not null default now(),
  updated_at timestamp
);

create table if not exists public.clubs (
  id serial primary key,
  name text not null,
  description text,
  address text,
  phone text,
  email text,
  logo_url text,
  cover_url text,
  is_active boolean not null default true,
  created_at timestamp not null default now(),
  updated_at timestamp
);

create table if not exists public.terrains (
  id serial primary key,
  name text not null,
  description text,
  type public.terrain_type not null,
  is_active boolean not null default true,
  price_per_person real not null default 25 check (price_per_person >= 0),
  capacity integer not null default 4 check (capacity > 0),
  opening_time text not null default '08:00',
  closing_time text not null default '23:00',
  photos text[] not null default '{}',
  created_at timestamp not null default now()
);

create table if not exists public.reservations (
  id serial primary key,
  terrain_id integer not null references public.terrains(id),
  user_id integer references public.users(id),
  guest_name text,
  guest_phone text,
  start_time timestamp not null,
  end_time timestamp not null,
  status public.reservation_status not null default 'confirmed',
  tokens_charged integer not null default 1 check (tokens_charged >= 0),
  booking_type public.booking_type not null default 'online',
  booking_mode public.booking_mode not null default 'full_court',
  total_spots integer not null default 4 check (total_spots > 0),
  is_public boolean not null default false,
  public_description text,
  notes text,
  created_at timestamp not null default now(),
  constraint reservations_valid_time check (end_time > start_time)
);

create table if not exists public.reservation_players (
  id serial primary key,
  reservation_id integer not null references public.reservations(id) on delete cascade,
  user_id integer not null references public.users(id),
  payment_type public.player_payment_type not null default 'token',
  payment_status public.player_payment_status not null default 'paid',
  tokens_charged integer not null default 1 check (tokens_charged >= 0),
  notes text,
  joined_at timestamp not null default now(),
  unique (reservation_id, user_id)
);

create table if not exists public.player_invites (
  id serial primary key,
  invite_token text not null unique,
  reservation_id integer not null references public.reservations(id) on delete cascade,
  invited_by_user_id integer not null references public.users(id),
  invited_email text,
  expires_at timestamp not null,
  status public.invite_status not null default 'pending',
  created_at timestamp not null default now()
);

create table if not exists public.token_transactions (
  id serial primary key,
  user_id integer not null references public.users(id),
  admin_id integer references public.users(id),
  reservation_id integer references public.reservations(id),
  type public.token_type not null,
  amount integer not null check (amount >= 0),
  balance_after integer not null check (balance_after >= 0),
  description text not null,
  notes text,
  expires_at timestamp,
  created_at timestamp not null default now()
);

create table if not exists public.notifications (
  id serial primary key,
  user_id integer not null references public.users(id),
  type public.notification_type not null,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamp not null default now()
);

create table if not exists public.tournaments (
  id serial primary key,
  name text not null,
  description text,
  status public.tournament_status not null default 'upcoming',
  start_date timestamp not null,
  end_date timestamp,
  max_teams integer check (max_teams is null or max_teams > 0),
  registered_teams integer not null default 0 check (registered_teams >= 0),
  prize_info text,
  image_url text,
  created_at timestamp not null default now()
);

create table if not exists public.tournament_registrations (
  id serial primary key,
  tournament_id integer not null references public.tournaments(id),
  user_id integer not null references public.users(id),
  team_name text,
  created_at timestamp not null default now(),
  unique (tournament_id, user_id)
);

create table if not exists public.news (
  id serial primary key,
  title text not null,
  content text not null,
  excerpt text,
  image_url text,
  published boolean not null default false,
  created_at timestamp not null default now(),
  updated_at timestamp
);

create table if not exists public.activity (
  id serial primary key,
  type text not null,
  message text not null,
  user_id integer,
  user_name text,
  created_at timestamp not null default now()
);

create table if not exists public.staff_roles (
  id serial primary key,
  user_id integer not null references public.users(id) on delete cascade,
  role text not null,
  created_at timestamp not null default now(),
  unique (user_id, role)
);

create unique index if not exists reservations_terrain_start_confirmed_idx
  on public.reservations (terrain_id, start_time)
  where status = 'confirmed';
create index if not exists reservations_user_start_idx on public.reservations (user_id, start_time desc);
create index if not exists reservations_public_start_idx on public.reservations (is_public, start_time) where is_public = true;
create index if not exists reservation_players_user_idx on public.reservation_players (user_id);
create index if not exists token_transactions_user_created_idx on public.token_transactions (user_id, created_at desc);
create index if not exists notifications_user_read_created_idx on public.notifications (user_id, is_read, created_at desc);
create index if not exists tournaments_status_start_idx on public.tournaments (status, start_date);

create or replace view public.open_matches as
select r.*
from public.reservations r
where r.is_public = true and r.status = 'confirmed' and r.start_time >= now();

create or replace function public.current_app_user_id()
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select id from public.users where supabase_auth_id = auth.uid()::text
$$;

create or replace function public.current_app_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.users where supabase_auth_id = auth.uid()::text and role = 'admin'
  )
$$;

create or replace function public.protect_user_accounting_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.current_app_user_is_admin() then
    return new;
  end if;

  if new.role <> old.role or new.token_balance <> old.token_balance or new.supabase_auth_id <> old.supabase_auth_id then
    raise exception 'Only admins may update role, token balance, or auth identity';
  end if;

  return new;
end;
$$;

drop trigger if exists protect_user_accounting_fields on public.users;
create trigger protect_user_accounting_fields
before update on public.users
for each row execute function public.protect_user_accounting_fields();

alter table public.users enable row level security;
alter table public.reservations enable row level security;
alter table public.reservation_players enable row level security;
alter table public.player_invites enable row level security;
alter table public.token_transactions enable row level security;
alter table public.notifications enable row level security;
alter table public.tournaments enable row level security;
alter table public.tournament_registrations enable row level security;
alter table public.terrains enable row level security;
alter table public.clubs enable row level security;
alter table public.news enable row level security;

create policy "users select own or admin" on public.users for select using (supabase_auth_id = auth.uid()::text or public.current_app_user_is_admin());
create policy "users update own profile" on public.users for update using (supabase_auth_id = auth.uid()::text) with check (supabase_auth_id = auth.uid()::text);
create policy "users admin all" on public.users for all using (public.current_app_user_is_admin()) with check (public.current_app_user_is_admin());

create policy "reservations visible to owner players public or admin" on public.reservations for select using (
  public.current_app_user_is_admin()
  or user_id = public.current_app_user_id()
  or is_public = true
  or exists (
    select 1 from public.reservation_players rp
    where rp.reservation_id = reservations.id and rp.user_id = public.current_app_user_id()
  )
);
create policy "reservations insert own" on public.reservations for insert with check (user_id = public.current_app_user_id());
create policy "reservations update owner or admin" on public.reservations for update using (public.current_app_user_is_admin() or user_id = public.current_app_user_id());

create policy "reservation players visible to participants or admin" on public.reservation_players for select using (
  public.current_app_user_is_admin()
  or user_id = public.current_app_user_id()
  or exists (
    select 1 from public.reservations r
    where r.id = reservation_players.reservation_id and r.user_id = public.current_app_user_id()
  )
);
create policy "reservation players insert self" on public.reservation_players for insert with check (user_id = public.current_app_user_id() or public.current_app_user_is_admin());
create policy "reservation players update admin only" on public.reservation_players for update using (public.current_app_user_is_admin()) with check (public.current_app_user_is_admin());

create policy "invites visible to creator reservation owner or admin" on public.player_invites for select using (
  public.current_app_user_is_admin()
  or invited_by_user_id = public.current_app_user_id()
  or exists (
    select 1 from public.reservations r
    where r.id = player_invites.reservation_id and r.user_id = public.current_app_user_id()
  )
);
create policy "invites create by authenticated users" on public.player_invites for insert with check (invited_by_user_id = public.current_app_user_id());
create policy "invites update by creator or admin" on public.player_invites for update using (public.current_app_user_is_admin() or invited_by_user_id = public.current_app_user_id());

create policy "token transactions select own or admin" on public.token_transactions for select using (public.current_app_user_is_admin() or user_id = public.current_app_user_id());
create policy "token transactions admin insert only" on public.token_transactions for insert with check (public.current_app_user_is_admin());
create policy "token transactions immutable except admin" on public.token_transactions for update using (false);

create policy "notifications select own or admin" on public.notifications for select using (public.current_app_user_is_admin() or user_id = public.current_app_user_id());
create policy "notifications update own read state" on public.notifications for update using (user_id = public.current_app_user_id()) with check (user_id = public.current_app_user_id());
create policy "notifications admin insert" on public.notifications for insert with check (public.current_app_user_is_admin());

create policy "tournaments public read" on public.tournaments for select using (true);
create policy "tournaments admin write" on public.tournaments for all using (public.current_app_user_is_admin()) with check (public.current_app_user_is_admin());
create policy "tournament registrations own or admin read" on public.tournament_registrations for select using (public.current_app_user_is_admin() or user_id = public.current_app_user_id());
create policy "tournament registrations insert own" on public.tournament_registrations for insert with check (user_id = public.current_app_user_id());

create policy "terrains public read" on public.terrains for select using (true);
create policy "terrains admin write" on public.terrains for all using (public.current_app_user_is_admin()) with check (public.current_app_user_is_admin());
create policy "clubs public read" on public.clubs for select using (true);
create policy "clubs admin write" on public.clubs for all using (public.current_app_user_is_admin()) with check (public.current_app_user_is_admin());
create policy "news public published read" on public.news for select using (published = true or public.current_app_user_is_admin());
create policy "news admin write" on public.news for all using (public.current_app_user_is_admin()) with check (public.current_app_user_is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/avif']),
  ('clubs', 'clubs', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/avif']),
  ('courts', 'courts', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/avif']),
  ('tournaments', 'tournaments', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/avif']),
  ('gallery', 'gallery', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/avif'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy "public image read" on storage.objects for select using (bucket_id in ('avatars', 'clubs', 'courts', 'tournaments', 'gallery'));
create policy "own avatar upload" on storage.objects for insert with check (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "own avatar update" on storage.objects for update using (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "admin media upload" on storage.objects for insert with check (bucket_id in ('clubs', 'courts', 'tournaments', 'gallery') and public.current_app_user_is_admin());
create policy "admin media update" on storage.objects for update using (bucket_id in ('clubs', 'courts', 'tournaments', 'gallery') and public.current_app_user_is_admin());
create policy "admin media delete" on storage.objects for delete using (bucket_id in ('clubs', 'courts', 'tournaments', 'gallery') and public.current_app_user_is_admin());

alter publication supabase_realtime add table public.reservations;
alter publication supabase_realtime add table public.reservation_players;
alter publication supabase_realtime add table public.player_invites;
alter publication supabase_realtime add table public.notifications;
alter publication supabase_realtime add table public.token_transactions;
alter publication supabase_realtime add table public.users;
insert into supabase_migrations.schema_migrations (version, name) values ('20260527190000', 'production_schema') on conflict (version) do nothing;

-- ===== 20260610000000_align_schema_with_drizzle.sql =====
-- Align news table with Drizzle schema
ALTER TABLE public.news RENAME COLUMN published TO is_published;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS published_at timestamp;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.news ADD COLUMN IF NOT EXISTS excerpt text;

-- Align activity table with Drizzle enum if possible, or ensure compatibility
-- Drizzle uses: reservation_created, reservation_cancelled, token_credited, token_debited, user_registered
-- Current SQL uses text. We'll keep text but add a check constraint for safety.
ALTER TABLE public.activity ADD CONSTRAINT activity_type_check 
CHECK (type IN ('reservation_created', 'reservation_cancelled', 'token_credited', 'token_debited', 'user_registered'));

-- Align staff_roles table
-- Drizzle uses: manager, coach, receptionist, maintenance
-- Current SQL uses plain text.
ALTER TABLE public.staff_roles ADD COLUMN IF NOT EXISTS role_type text;
ALTER TABLE public.staff_roles ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.staff_roles ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;

-- Update RLS for news to use the new column name
DROP POLICY IF EXISTS "news public published read" ON public.news;
CREATE POLICY "news public published read" ON public.news 
FOR SELECT USING (is_published = true OR public.current_app_user_is_admin());

-- Add missing constraints to reservations to match Drizzle/Business logic if not present
-- (Note: some were already in the previous migration, adding others)
ALTER TABLE public.reservations ALTER COLUMN tokens_charged SET DEFAULT 1;
ALTER TABLE public.reservations ALTER COLUMN total_spots SET DEFAULT 4;

-- Ensure reservation_players has the unique constraint
-- (Already in migration but good to be sure)
-- ALTER TABLE public.reservation_players ADD CONSTRAINT reservation_players_res_user_unique UNIQUE (reservation_id, user_id);
insert into supabase_migrations.schema_migrations (version, name) values ('20260610000000', 'align_schema_with_drizzle') on conflict (version) do nothing;

-- ===== 20261001000000_pricing_equipment_series_notifications.sql =====
-- ============================================================================
-- Peak / off-peak pricing, equipment rental, recurring bookings,
-- notification preferences, web push and an idempotent notification log.
-- Times in pricing rules are club-local wall-clock times ("HH:MM", Africa/Tunis).
-- ============================================================================

-- ─── Fix: let the API server manage token balances ──────────────────────────
-- protect_user_accounting_fields() must stop players from editing their own
-- balance through PostgREST (roles anon / authenticated). The Express API connects
-- directly with a privileged role and no Supabase JWT, so the previous version
-- rejected every booking debit and cancellation refund made by the API.
create or replace function public.protect_user_accounting_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Trusted server-side connections (API, migrations, dashboard SQL).
  -- PostgREST logs in as "authenticator" then SET ROLE anon/authenticated; this is
  -- SECURITY DEFINER, so current_user is the owner and can't be used here.
  if session_user <> 'authenticator'
     and coalesce(current_setting('role', true), 'none') not in ('anon', 'authenticated') then
    return new;
  end if;

  if public.current_app_user_is_admin() then
    return new;
  end if;

  if new.role <> old.role or new.token_balance <> old.token_balance or new.supabase_auth_id <> old.supabase_auth_id then
    raise exception 'Only admins may update role, token balance, or auth identity';
  end if;

  return new;
end;
$$;

-- ─── Notification types ─────────────────────────────────────────────────────
alter type public.notification_type add value if not exists 'match_finished';
alter type public.notification_type add value if not exists 'welcome';

-- ─── User preferences ───────────────────────────────────────────────────────
alter table public.users add column if not exists email_notifications boolean not null default true;
alter table public.users add column if not exists push_notifications boolean not null default true;

-- ─── Pricing rules ──────────────────────────────────────────────────────────
-- A rule applies when the slot's local weekday is in days_of_week (0 = Sunday)
-- and its local start time is in [start_time, end_time). terrain_id NULL = all courts.
-- When several rules match, the highest priority wins (court-specific rules first).
create table if not exists public.pricing_rules (
  id serial primary key,
  name text not null,
  terrain_id integer references public.terrains(id) on delete cascade,
  days_of_week smallint[] not null default '{0,1,2,3,4,5,6}',
  start_time text not null check (start_time ~ '^\d{2}:\d{2}$'),
  end_time text not null check (end_time ~ '^\d{2}:\d{2}$'),
  tokens_per_spot integer not null default 1 check (tokens_per_spot between 1 and 10),
  price_per_person real,
  is_peak boolean not null default false,
  priority integer not null default 0,
  is_active boolean not null default true,
  created_at timestamp not null default now(),
  check (start_time < end_time)
);
create index if not exists pricing_rules_active_idx on public.pricing_rules (is_active, terrain_id);

-- ─── Equipment rental ───────────────────────────────────────────────────────
create table if not exists public.equipment_items (
  id serial primary key,
  name text not null,
  description text,
  category text not null default 'racket',
  price real not null default 0 check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  is_active boolean not null default true,
  created_at timestamp not null default now()
);

do $$ begin
  create type public.rental_status as enum ('reserved', 'handed_out', 'returned', 'cancelled');
exception when duplicate_object then null; end $$;

create table if not exists public.reservation_equipment (
  id serial primary key,
  reservation_id integer not null references public.reservations(id) on delete cascade,
  item_id integer not null references public.equipment_items(id),
  user_id integer references public.users(id),
  quantity integer not null default 1 check (quantity between 1 and 8),
  unit_price real not null default 0,
  status public.rental_status not null default 'reserved',
  created_at timestamp not null default now()
);
create index if not exists reservation_equipment_reservation_idx on public.reservation_equipment (reservation_id);
create index if not exists reservation_equipment_item_idx on public.reservation_equipment (item_id, status);

-- ─── Recurring bookings ─────────────────────────────────────────────────────
do $$ begin
  create type public.series_status as enum ('active', 'cancelled');
exception when duplicate_object then null; end $$;

create table if not exists public.reservation_series (
  id serial primary key,
  terrain_id integer not null references public.terrains(id),
  user_id integer references public.users(id),
  guest_name text,
  guest_phone text,
  label text,
  first_start timestamp not null,
  occurrences integer not null check (occurrences between 2 and 52),
  interval_weeks integer not null default 1 check (interval_weeks between 1 and 4),
  notes text,
  status public.series_status not null default 'active',
  created_by integer references public.users(id),
  created_at timestamp not null default now()
);
alter table public.reservations add column if not exists series_id integer references public.reservation_series(id) on delete set null;
create index if not exists reservations_series_idx on public.reservations (series_id);

-- ─── Web push ───────────────────────────────────────────────────────────────
create table if not exists public.push_subscriptions (
  id serial primary key,
  user_id integer not null references public.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamp not null default now()
);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions (user_id);

-- ─── Notification log (idempotency for emails, push and scheduled jobs) ─────
create table if not exists public.notification_log (
  id serial primary key,
  user_id integer not null references public.users(id) on delete cascade,
  kind text not null,
  ref text not null default '',
  channels text[] not null default '{}',
  created_at timestamp not null default now(),
  unique (user_id, kind, ref)
);

-- ─── Row level security ─────────────────────────────────────────────────────
-- The API connects with a privileged role; these policies only govern direct
-- PostgREST access with the anon/authenticated keys.
alter table public.pricing_rules enable row level security;
alter table public.equipment_items enable row level security;
alter table public.reservation_equipment enable row level security;
alter table public.reservation_series enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.notification_log enable row level security;

drop policy if exists "pricing public read" on public.pricing_rules;
create policy "pricing public read" on public.pricing_rules for select using (is_active or public.current_app_user_is_admin());
drop policy if exists "equipment public read" on public.equipment_items;
create policy "equipment public read" on public.equipment_items for select using (is_active or public.current_app_user_is_admin());
drop policy if exists "rentals admin read" on public.reservation_equipment;
create policy "rentals admin read" on public.reservation_equipment for select using (public.current_app_user_is_admin());
drop policy if exists "series admin read" on public.reservation_series;
create policy "series admin read" on public.reservation_series for select using (public.current_app_user_is_admin());
-- push_subscriptions and notification_log: no policies = no direct client access.
insert into supabase_migrations.schema_migrations (version, name) values ('20261001000000', 'pricing_equipment_series_notifications') on conflict (version) do nothing;

-- ===== 20261002000000_security_and_integrity.sql =====
-- ============================================================================
-- Security & data-integrity hardening for production.
--
-- Access model: the browser talks to Supabase for AUTH ONLY. Every read/write of
-- club data goes through the Express API, which connects with DATABASE_URL (a
-- privileged role that bypasses RLS) and enforces business rules server-side.
-- Therefore the anon / authenticated roles get NO direct access to public tables.
-- ============================================================================

-- ─── 1. Per-player payment states ───────────────────────────────────────────
-- payment_type is HOW the spot is paid:  token | cash_club | invited_free
-- payment_status is WHERE it stands:     paid | pending | refunded
do $$ begin
  if exists (
    select 1 from pg_enum e join pg_type t on t.oid = e.enumtypid
    where t.typname = 'player_payment_type' and e.enumlabel = 'cash'
  ) then
    alter type public.player_payment_type rename value 'cash' to 'cash_club';
  end if;
end $$;
alter type public.player_payment_type add value if not exists 'invited_free';

-- ─── 2. Two bookings can never overlap on the same court ────────────────────
-- The old unique index only caught identical start times (18:30 vs 18:30), not
-- overlapping ones (18:30 vs 19:00). An exclusion constraint makes the database
-- reject any overlap, whatever the application does (error 23P01).
create extension if not exists btree_gist with schema extensions;

alter table public.reservations drop constraint if exists reservations_no_overlap;
alter table public.reservations add constraint reservations_no_overlap
  exclude using gist (
    terrain_id extensions.gist_int4_ops with =,
    tsrange(start_time, end_time, '[)') with &&
  ) where (status = 'confirmed');

-- ─── 3. A match never has more players than spots ───────────────────────────
create or replace function public.enforce_reservation_capacity()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  cap integer;
  taken integer;
begin
  -- Row lock serializes concurrent joins on the same reservation
  select total_spots into cap from public.reservations where id = new.reservation_id for update;
  select count(*) into taken from public.reservation_players where reservation_id = new.reservation_id;
  if taken >= cap then
    raise exception 'Reservation % is full', new.reservation_id
      using errcode = 'P0001', hint = 'RESERVATION_FULL';
  end if;
  return new;
end;
$$;

drop trigger if exists reservation_players_capacity on public.reservation_players;
create trigger reservation_players_capacity
before insert on public.reservation_players
for each row execute function public.enforce_reservation_capacity();

-- ─── 4. Token ledger ────────────────────────────────────────────────────────
-- 4a. The ledger is append-only: no edits, no deletions.
create or replace function public.token_transactions_append_only()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'token_transactions is append-only (% refused)', tg_op using errcode = 'P0001';
end;
$$;

drop trigger if exists token_transactions_append_only on public.token_transactions;
create trigger token_transactions_append_only
before update or delete on public.token_transactions
for each row execute function public.token_transactions_append_only();

-- 4b. Every balance change must be recorded: at COMMIT, the user's latest ledger
-- entry must carry the user's final balance. A balance edited without a matching
-- transaction aborts the whole transaction.
create or replace function public.assert_token_balance_recorded()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  current_balance integer;
  last_after integer;
begin
  select token_balance into current_balance from public.users where id = new.id;
  select balance_after into last_after
    from public.token_transactions where user_id = new.id
    order by id desc limit 1;
  if last_after is distinct from current_balance then
    raise exception 'Token balance of user % changed without a ledger entry', new.id
      using errcode = 'P0001', hint = 'TOKEN_LEDGER_MISMATCH';
  end if;
  return null;
end;
$$;

drop trigger if exists users_token_balance_ledger on public.users;
create constraint trigger users_token_balance_ledger
after update of token_balance on public.users
deferrable initially deferred
for each row
when (old.token_balance is distinct from new.token_balance)
execute function public.assert_token_balance_recorded();

-- 4c. Idempotency: the same admin action (double click, network retry) can't credit twice.
alter table public.token_transactions add column if not exists idempotency_key text;
create unique index if not exists token_transactions_idempotency_key_idx
  on public.token_transactions (idempotency_key) where idempotency_key is not null;

-- 4d. Audit view: users whose balance doesn't match their last ledger entry (should be empty).
create or replace view public.token_ledger_audit
with (security_invoker = true) as
select u.id as user_id, u.email, u.token_balance,
       (select t.balance_after from public.token_transactions t
         where t.user_id = u.id order by t.id desc limit 1) as last_balance_after
from public.users u
where u.token_balance <> coalesce(
  (select t.balance_after from public.token_transactions t
    where t.user_id = u.id order by t.id desc limit 1), 0);

-- ─── 5. Player profile is created by the database at signup ─────────────────
-- (The API's POST /users/sync stays as an idempotent fallback.)
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  meta jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  full_name text := nullif(trim(coalesce(meta->>'full_name', meta->>'name', '')), '');
begin
  -- Same email re-registered after its previous auth account was deleted: relink.
  update public.users u
     set supabase_auth_id = new.id::text, updated_at = now()
   where new.email is not null
     and lower(u.email) = lower(new.email)
     and not exists (select 1 from auth.users a where a.id::text = u.supabase_auth_id);
  if found then
    return new;
  end if;

  insert into public.users (supabase_auth_id, email, first_name, last_name, phone, avatar_url)
  values (
    new.id::text,
    coalesce(new.email, new.id::text || '@placeholder.local'),
    left(nullif(trim(coalesce(meta->>'first_name', split_part(full_name, ' ', 1), '')), ''), 80),
    left(nullif(trim(coalesce(meta->>'last_name',
      nullif(substr(full_name, length(split_part(full_name, ' ', 1)) + 2), ''), '')), ''), 80),
    left(nullif(trim(coalesce(meta->>'phone', '')), ''), 30),
    nullif(meta->>'avatar_url', '')
  )
  on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_app on auth.users;
create trigger on_auth_user_created_app
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create or replace function public.handle_auth_email_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.users set email = new.email, updated_at = now()
   where supabase_auth_id = new.id::text and new.email is not null;
  return new;
end;
$$;

drop trigger if exists on_auth_user_email_changed_app on auth.users;
create trigger on_auth_user_email_changed_app
after update of email on auth.users
for each row
when (old.email is distinct from new.email)
execute function public.handle_auth_email_change();

-- ─── 6. Lock down direct (PostgREST / Realtime) access ──────────────────────
-- Drop every permissive policy: several allowed players to insert reservations or
-- add themselves to a match as "paid" without paying, straight from the browser.
do $$
declare
  r record;
begin
  for r in select tablename, policyname from pg_policies where schemaname = 'public' loop
    execute format('drop policy if exists %I on public.%I', r.policyname, r.tablename);
  end loop;
  for r in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', r.tablename);
  end loop;
end $$;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke execute on all functions in schema public from anon, authenticated, public;

-- Tables, sequences and functions created later by the postgres role are private too.
alter default privileges for role postgres in schema public revoke all on tables from anon, authenticated;
alter default privileges for role postgres in schema public revoke all on sequences from anon, authenticated;
alter default privileges for role postgres in schema public revoke execute on functions from anon, authenticated, public;

-- The app doesn't use Realtime (it polls the API), so publish nothing from public.
do $$
declare
  r record;
begin
  for r in
    select tablename from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public'
  loop
    execute format('alter publication supabase_realtime drop table public.%I', r.tablename);
  end loop;
end $$;

-- open_matches view: run with the caller's rights (it ran as owner and bypassed RLS).
drop view if exists public.open_matches;
create view public.open_matches with (security_invoker = true) as
select r.*
from public.reservations r
where r.is_public = true and r.status = 'confirmed' and r.start_time >= now();
revoke all on public.open_matches, public.token_ledger_audit from anon, authenticated;

-- Storage: the app never uploads from the browser. Public buckets keep serving files
-- by public URL; listing and browser-side writes are closed.
drop policy if exists "public image read" on storage.objects;
drop policy if exists "own avatar upload" on storage.objects;
drop policy if exists "own avatar update" on storage.objects;
drop policy if exists "admin media upload" on storage.objects;
drop policy if exists "admin media update" on storage.objects;
drop policy if exists "admin media delete" on storage.objects;

-- ─── 7. Indexes for foreign keys and hot queries ────────────────────────────
create index if not exists reservations_status_start_idx on public.reservations (status, start_time);
create index if not exists reservations_terrain_idx on public.reservations (terrain_id);
create index if not exists token_transactions_reservation_idx on public.token_transactions (reservation_id);
create index if not exists token_transactions_admin_idx on public.token_transactions (admin_id);
create index if not exists player_invites_reservation_idx on public.player_invites (reservation_id);
create index if not exists player_invites_invited_by_idx on public.player_invites (invited_by_user_id);
create index if not exists tournament_registrations_user_idx on public.tournament_registrations (user_id);
create index if not exists reservation_series_terrain_idx on public.reservation_series (terrain_id);
create index if not exists reservation_series_user_idx on public.reservation_series (user_id);
create index if not exists reservation_series_created_by_idx on public.reservation_series (created_by);
create index if not exists reservation_equipment_user_idx on public.reservation_equipment (user_id);
create index if not exists pricing_rules_terrain_idx on public.pricing_rules (terrain_id);
insert into supabase_migrations.schema_migrations (version, name) values ('20261002000000', 'security_and_integrity') on conflict (version) do nothing;

-- ===== 20261003000000_club_settings.sql =====
-- ============================================================================
-- Operational settings for ONE club installation (no tenant / club id: each club
-- has its own database). Everything an owner may change while running the club
-- lives here and is edited from Admin → Réglages. Branding (name, logo, colours,
-- photos) is NOT here: it's design-time configuration of each installation.
--
-- Additive migration: new tables, new nullable columns, relaxed NOT NULLs. The
-- only data touched: court hours/prices equal to the old hard-coded defaults are
-- turned into "use club setting" (NULL), which yields exactly the same behaviour.
-- ============================================================================

-- ─── 1. Club settings: a single row (id = 1) ────────────────────────────────
create table if not exists public.club_settings (
  id smallint primary key default 1 check (id = 1),

  -- Booking
  booking_duration_minutes integer not null default 90
    check (booking_duration_minutes between 30 and 240 and booking_duration_minutes % 5 = 0),
  min_players integer not null default 1 check (min_players between 1 and 8),
  max_players integer not null default 4 check (max_players between 1 and 8),
  min_advance_minutes integer not null default 30 check (min_advance_minutes between 0 and 10080),
  max_advance_days integer not null default 14 check (max_advance_days between 1 and 365),

  -- Cancellation: players cancel (or leave) with a full token refund until
  -- cancellation_notice_hours before the match. After that: 'forbid' or 'no_refund'.
  cancellation_notice_hours integer not null default 0 check (cancellation_notice_hours between 0 and 168),
  late_cancellation text not null default 'forbid' check (late_cancellation in ('forbid', 'no_refund')),

  -- Pricing (cash prices at the desk, in `currency`)
  currency text not null default 'TND' check (currency ~ '^[A-Z]{3}$'),
  player_price numeric(10, 2) not null default 25 check (player_price >= 0),
  full_court_price numeric(10, 2) not null default 100 check (full_court_price >= 0),

  -- Tokens
  token_cost_player integer not null default 1 check (token_cost_player between 0 and 100),
  token_cost_full_court integer not null default 4 check (token_cost_full_court between 0 and 400),
  token_unit_price numeric(10, 2) not null default 25 check (token_unit_price >= 0),
  token_min_purchase integer not null default 1 check (token_min_purchase between 1 and 1000),

  -- Features
  open_matches_enabled boolean not null default true,
  invitations_enabled boolean not null default true,
  cash_payment_enabled boolean not null default true,

  -- Notifications (in-app + email + push, each member still picks channels in their profile)
  booking_confirmation_notifications_enabled boolean not null default true,
  reminders_enabled boolean not null default true,
  reminder_lead_minutes integer not null default 120 check (reminder_lead_minutes between 15 and 1440),
  cancellation_notifications_enabled boolean not null default true,
  invitation_notifications_enabled boolean not null default true,
  token_notifications_enabled boolean not null default true,
  match_finished_notifications_enabled boolean not null default true,

  updated_at timestamp not null default now(),
  updated_by integer references public.users(id) on delete set null,

  constraint club_settings_players check (min_players <= max_players)
);
insert into public.club_settings (id) values (1) on conflict (id) do nothing;

-- ─── 2. Weekly opening hours (0 = Sunday … 6 = Saturday) ────────────────────
create table if not exists public.opening_hours (
  weekday smallint primary key check (weekday between 0 and 6),
  is_closed boolean not null default false,
  open_time text not null default '08:00' check (open_time ~ '^([01]\d|2[0-3]):[0-5]\d$'),
  close_time text not null default '23:00' check (close_time ~ '^([01]\d|2[0-3]):[0-5]\d$|^24:00$'),
  constraint opening_hours_order check (is_closed or open_time < close_time)
);
insert into public.opening_hours (weekday)
select g from generate_series(0, 6) g
on conflict (weekday) do nothing;

-- ─── 3. Exceptions: holidays, exceptional hours, maintenance days ──────────
-- terrain_id NULL = whole club. is_closed = nothing bookable that day; otherwise
-- open_time/close_time replace the normal hours for that date.
create table if not exists public.schedule_exceptions (
  id serial primary key,
  date date not null,
  terrain_id integer references public.terrains(id) on delete cascade,
  is_closed boolean not null default true,
  open_time text check (open_time ~ '^([01]\d|2[0-3]):[0-5]\d$'),
  close_time text check (close_time ~ '^([01]\d|2[0-3]):[0-5]\d$|^24:00$'),
  reason text,
  created_at timestamp not null default now(),
  constraint schedule_exceptions_hours check (
    is_closed or (open_time is not null and close_time is not null and open_time < close_time)
  )
);
create unique index if not exists schedule_exceptions_day_court_idx
  on public.schedule_exceptions (date, coalesce(terrain_id, 0));
create index if not exists schedule_exceptions_terrain_idx on public.schedule_exceptions (terrain_id);

-- ─── 4. Token packages sold at the desk (10 tokens = 250 TND …) ────────────
create table if not exists public.token_packages (
  id serial primary key,
  name text not null,
  tokens integer not null check (tokens between 1 and 1000),
  price numeric(10, 2) not null check (price >= 0),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamp not null default now()
);
insert into public.token_packages (name, tokens, price, sort_order)
select * from (values ('Pack 10', 10, 250.00, 1), ('Pack 20', 20, 480.00, 2), ('Pack 50', 50, 1150.00, 3)) v
where not exists (select 1 from public.token_packages);

-- Cash received for a credit (accounting), and which package was sold
alter table public.token_transactions add column if not exists cash_amount numeric(10, 2) check (cash_amount >= 0);
alter table public.token_transactions add column if not exists package_id integer references public.token_packages(id) on delete set null;
create index if not exists token_transactions_package_idx on public.token_transactions (package_id);

-- ─── 5. Courts: number, order, maintenance, archive, optional overrides ────
alter table public.terrains add column if not exists number integer;
alter table public.terrains add column if not exists sort_order integer not null default 0;
alter table public.terrains add column if not exists is_maintenance boolean not null default false;
alter table public.terrains add column if not exists maintenance_note text;
alter table public.terrains add column if not exists archived_at timestamp;

-- Price and hours become optional per-court overrides of the club settings
alter table public.terrains alter column price_per_person drop not null;
alter table public.terrains alter column price_per_person drop default;
alter table public.terrains alter column opening_time drop not null;
alter table public.terrains alter column opening_time drop default;
alter table public.terrains alter column closing_time drop not null;
alter table public.terrains alter column closing_time drop default;
update public.terrains set price_per_person = null where price_per_person = 25;
update public.terrains set opening_time = null, closing_time = null
 where opening_time = '08:00' and closing_time = '23:00';
update public.terrains set sort_order = id where sort_order = 0;

-- ─── 6. Invitations: invite a member in-app, who can accept or decline ─────
alter type public.invite_status add value if not exists 'declined';
alter type public.notification_type add value if not exists 'invitation';
alter table public.player_invites add column if not exists invited_user_id integer references public.users(id) on delete cascade;
alter table public.player_invites add column if not exists responded_at timestamp;
create index if not exists player_invites_invited_user_idx on public.player_invites (invited_user_id, status);
-- One open personal invitation per member and match
create unique index if not exists player_invites_personal_pending_idx
  on public.player_invites (reservation_id, invited_user_id)
  where invited_user_id is not null and status = 'pending';

-- ─── 7. Activity log: settings changes are audited too ──────────────────────
alter table public.activity drop constraint if exists activity_type_check;
alter table public.activity add constraint activity_type_check check (type in (
  'reservation_created', 'reservation_cancelled', 'token_credited', 'token_debited',
  'user_registered', 'settings_updated'
));

-- ─── 8. Same lockdown as every other table: API-only access ────────────────
alter table public.club_settings enable row level security;
alter table public.opening_hours enable row level security;
alter table public.schedule_exceptions enable row level security;
alter table public.token_packages enable row level security;
revoke all on public.club_settings, public.opening_hours, public.schedule_exceptions, public.token_packages
  from anon, authenticated;
revoke all on sequence public.schedule_exceptions_id_seq, public.token_packages_id_seq from anon, authenticated;
insert into supabase_migrations.schema_migrations (version, name) values ('20261003000000', 'club_settings') on conflict (version) do nothing;
commit;
