/**
 * Prints every migration as ONE transaction, plus the migration-history rows, ready
 * to paste into the Supabase SQL editor (Dashboard → SQL Editor → Run):
 *
 *   pnpm --silent --filter @workspace/scripts run db:bundle > apply.sql
 *
 * One-time use, on a database that has none of these migrations yet (the hosted
 * project today). It also removes the history rows of the legacy prototype schema
 * (applied outside this repo on 2026-06-29) so `supabase db push` agrees with
 * supabase/migrations/. Later migrations: use `db:migrate` or `supabase db push`.
 * If anything fails the whole transaction rolls back and nothing changes.
 */
import { readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..", "..");
const dir = resolve(root, "supabase", "migrations");
const LEGACY = [
  "20260629151213",
  "20260629151226",
  "20260629151237",
  "20260629151248",
  "20260629151301",
];

const out = [
  "-- Generated by scripts/src/bundle-migrations.ts — do not edit, regenerate instead.",
  "begin;",
  "set local lock_timeout = '10s';",
  "create schema if not exists supabase_migrations;",
  "create table if not exists supabase_migrations.schema_migrations (version text primary key, statements text[], name text);",
  `delete from supabase_migrations.schema_migrations where version in (${LEGACY.map((v) => `'${v}'`).join(", ")});`,
];
for (const file of readdirSync(dir)
  .filter((f) => /^\d{14}_.+\.sql$/.test(f))
  .sort()) {
  const [version, ...rest] = file.replace(/\.sql$/, "").split("_");
  out.push(`\n-- ===== ${file} =====`);
  out.push(readFileSync(resolve(dir, file), "utf8").trimEnd());
  out.push(
    `insert into supabase_migrations.schema_migrations (version, name) values ('${version}', '${rest.join("_")}') on conflict (version) do nothing;`,
  );
}
out.push("commit;");
process.stdout.write(out.join("\n") + "\n");
