// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/padel-redesign/DarkGlass.tsx": () => import("../components/mockups/padel-redesign/DarkGlass.tsx"),
  "./components/mockups/padel-redesign/PremiumImmersive.tsx": () => import("../components/mockups/padel-redesign/PremiumImmersive.tsx"),
  "./components/mockups/padel-redesign/SportyDynamic.tsx": () => import("../components/mockups/padel-redesign/SportyDynamic.tsx")
};
